# Generated by Django 3.2 on 2024-06-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='user_auth_type',
            field=models.CharField(choices=[('username/password', 'Username/Password'), ('google auth', 'Google Auth')], default='username/password', max_length=50),
        ),
        migrations.DeleteModel(
            name='registereduser',
        ),
    ]
