# Generated by Django 3.2 on 2024-06-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_auto_20240604_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applied_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Under consideration', 'Under Consideration'), ('Interviewing', 'Interviewing'), ('In progress', 'In Progress'), ('Rejected', 'Rejected'), ('Hired', 'Hired'), ('Closed', 'Closed')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('hybrid', 'Hybrid'), ('remote', 'Remote'), ('internship', 'Internship'), ('bonded', 'Bonded'), ('Wfh', 'Work-from-Home')], max_length=20),
        ),
    ]
