# Generated by Django 3.2 on 2024-07-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0002_alter_job_jobpost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
