# Generated by Django 3.2 on 2024-07-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_jobseeker_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
