# Generated by Django 3.2 on 2024-06-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0003_auto_20240619_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_desc',
            field=models.TextField(null=True),
        ),
    ]
