# Generated by Django 3.2 on 2024-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_alter_recruiter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='fresher',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
