# Generated by Django 3.2 on 2024-06-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0004_application_app_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
