# Generated by Django 3.2 on 2024-06-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0005_auto_20240620_0455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='fname',
            new_name='name',
        ),
    ]
