# Generated by Django 3.2 on 2024-06-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0006_rename_fname_jobseeker_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='lname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
