# Generated by Django 3.2 on 2024-06-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0007_recruiter_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='app_desc',
            new_name='remarks',
        ),
    ]
