# Generated by Django 3.2 on 2024-06-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0008_rename_app_desc_application_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_seeker',
            field=models.EmailField(max_length=254),
        ),
    ]
