# Generated by Django 3.2 on 2024-06-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0009_alter_application_job_seeker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='job_seeker',
            new_name='email',
        ),
    ]
