# Generated by Django 3.2 on 2024-06-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0010_rename_job_seeker_application_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='resume_path',
        ),
    ]
