# Generated by Django 3.2 on 2024-06-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobApp', '0011_remove_jobseeker_resume_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company_name',
        ),
    ]
